version: '3.8'

services:
  remix:
    build: .
    ports:
      - "3000:3000"
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      PORT: 3000
      VITE_PORT: 5173
    command: npm run dev
